/*
 * Author's name and email: Michael, michaeljava95@gmail.com
 * Program description: Built the book example using visual IDE tools.
 * Latest version: 2:22 AM, 1/16/2021
 * Older versions: 
 */

import javax.swing.JOptionPane;

public class ButtonFrame extends javax.swing.JFrame
{

	/**
	 * Creates new form ButtonFrame
	 */
	public ButtonFrame()
	{
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents()
   {

      plainButton = new javax.swing.JButton();
      fancyButton = new javax.swing.JButton();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setTitle("Testing Buttons");

      plainButton.setText("Plain Button");
      plainButton.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            plainButtonActionPerformed(evt);
         }
      });

      fancyButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bug1.GIF"))); // NOI18N
      fancyButton.setText("Fancy Button");
      fancyButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/bug2.GIF"))); // NOI18N
      fancyButton.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            fancyButtonActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(30, 30, 30)
            .addComponent(plainButton)
            .addGap(40, 40, 40)
            .addComponent(fancyButton)
            .addContainerGap(30, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(30, 30, 30)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(plainButton)
               .addComponent(fancyButton))
            .addContainerGap(30, Short.MAX_VALUE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void plainButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_plainButtonActionPerformed
   {//GEN-HEADEREND:event_plainButtonActionPerformed
      JOptionPane.showMessageDialog(rootPane, "You pressed: " + plainButton.getText());
   }//GEN-LAST:event_plainButtonActionPerformed

   private void fancyButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_fancyButtonActionPerformed
   {//GEN-HEADEREND:event_fancyButtonActionPerformed
      JOptionPane.showMessageDialog(rootPane, "You pressed: " + fancyButton.getText());
   }//GEN-LAST:event_fancyButtonActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[])
	{
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try
		{
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
			{
				if ("Nimbus".equals(info.getName()))
				{
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		}
		catch (ClassNotFoundException ex)
		{
			java.util.logging.Logger.getLogger(ButtonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		catch (InstantiationException ex)
		{
			java.util.logging.Logger.getLogger(ButtonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		catch (IllegalAccessException ex)
		{
			java.util.logging.Logger.getLogger(ButtonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		catch (javax.swing.UnsupportedLookAndFeelException ex)
		{
			java.util.logging.Logger.getLogger(ButtonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable()
		{
			public void run()
			{
				new ButtonFrame().setVisible(true);
			}
		});
	}

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton fancyButton;
   private javax.swing.JButton plainButton;
   // End of variables declaration//GEN-END:variables
}
