/*
 * Author's name and email: Michael, michaeljava95@gmail.com
 * Program description: Built the book example using visual IDE tools.
 * Latest version: 1:42 AM, 2/11/2021
 * Older versions: 
 */

import javax.swing.Icon;
import javax.swing.ImageIcon;

public class ComboBoxFrame extends javax.swing.JFrame
{
	private static final String[] names = { "bug1.gif", "bug2.gif", 
		"travelbug.gif", "buganim.gif" };
	private final Icon[] icons = {
		new ImageIcon(getClass().getResource(names[0])),
		new ImageIcon(getClass().getResource(names[1])),
		new ImageIcon(getClass().getResource(names[2])),
		new ImageIcon(getClass().getResource(names[3])) };

	/**
	 * Creates new form ComboBoxFrame
	 */
	public ComboBoxFrame()
	{
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents()
   {

      imagesJComboBox = new javax.swing.JComboBox<>();
      label = new javax.swing.JLabel();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setTitle("Testing JComboBox");

      imagesJComboBox.setMaximumRowCount(3);
      imagesJComboBox.setModel(new javax.swing.DefaultComboBoxModel(names));
      imagesJComboBox.addItemListener(new java.awt.event.ItemListener()
      {
         public void itemStateChanged(java.awt.event.ItemEvent evt)
         {
            imagesJComboBoxItemStateChanged(evt);
         }
      });
      imagesJComboBox.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            imagesJComboBoxActionPerformed(evt);
         }
      });

      label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bug1.GIF"))); // NOI18N

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(80, 80, 80)
            .addComponent(imagesJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(label)
            .addContainerGap(97, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(20, 20, 20)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(imagesJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(label))
            .addContainerGap(64, Short.MAX_VALUE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void imagesJComboBoxActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_imagesJComboBoxActionPerformed
   {//GEN-HEADEREND:event_imagesJComboBoxActionPerformed
      label.setIcon(icons[imagesJComboBox.getSelectedIndex()]);
   }//GEN-LAST:event_imagesJComboBoxActionPerformed

   private void imagesJComboBoxItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_imagesJComboBoxItemStateChanged
   {//GEN-HEADEREND:event_imagesJComboBoxItemStateChanged
      
   }//GEN-LAST:event_imagesJComboBoxItemStateChanged

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[])
	{
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try
		{
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
			{
				if ("Nimbus".equals(info.getName()))
				{
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		}
		catch (ClassNotFoundException ex)
		{
			java.util.logging.Logger.getLogger(ComboBoxFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		catch (InstantiationException ex)
		{
			java.util.logging.Logger.getLogger(ComboBoxFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		catch (IllegalAccessException ex)
		{
			java.util.logging.Logger.getLogger(ComboBoxFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		catch (javax.swing.UnsupportedLookAndFeelException ex)
		{
			java.util.logging.Logger.getLogger(ComboBoxFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable()
		{
			public void run()
			{
				new ComboBoxFrame().setVisible(true);
			}
		});
	}

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JComboBox<String> imagesJComboBox;
   private javax.swing.JLabel label;
   // End of variables declaration//GEN-END:variables
}
