/*
 * Author's name and email: Michael, michaeljava95@gmail.com
 * Program description: Built the book example using visual IDE tools.
 * Latest version: 7:12 PM, 2/18/2021
 * Older versions: 
 */

import java.awt.event.KeyEvent;

public class KeyDemoFrame extends javax.swing.JFrame
{
	private String line1 = ""; // first line of textarea
	private String line2 = ""; // second line of textarea
	private String line3 = ""; // third line of textarea

	/**
	 * Creates new form KeyDemoFrame
	 */
	public KeyDemoFrame()
	{
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents()
   {

      jScrollPane1 = new javax.swing.JScrollPane();
      textArea = new javax.swing.JTextArea();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setTitle("Demonstrating Keystroke Events");

      textArea.setEditable(false);
      textArea.setColumns(20);
      textArea.setRows(5);
      textArea.setText("Press any key on the keyboard...");
      textArea.setDisabledTextColor(new java.awt.Color(0, 0, 0));
      textArea.addKeyListener(new java.awt.event.KeyAdapter()
      {
         public void keyPressed(java.awt.event.KeyEvent evt)
         {
            textAreaKeyPressed(evt);
         }
         public void keyReleased(java.awt.event.KeyEvent evt)
         {
            textAreaKeyReleased(evt);
         }
         public void keyTyped(java.awt.event.KeyEvent evt)
         {
            textAreaKeyTyped(evt);
         }
      });
      jScrollPane1.setViewportView(textArea);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1)
            .addContainerGap())
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void textAreaKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_textAreaKeyPressed
   {//GEN-HEADEREND:event_textAreaKeyPressed
		line1 = String.format("Key pressed: %s",
			KeyEvent.getKeyText(evt.getKeyCode())); // show pressed key
		setLines2and3(evt); // set output lines two and three
   }//GEN-LAST:event_textAreaKeyPressed

   private void textAreaKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_textAreaKeyReleased
   {//GEN-HEADEREND:event_textAreaKeyReleased
		line1 = String.format("Key released: %s",
			KeyEvent.getKeyText(evt.getKeyCode())); // show released key
		setLines2and3(evt); // set output lines two and three
   }//GEN-LAST:event_textAreaKeyReleased

   private void textAreaKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_textAreaKeyTyped
   {//GEN-HEADEREND:event_textAreaKeyTyped
		line1 = String.format("Key typed: %s", evt.getKeyChar());
		setLines2and3(evt); // set output lines two and three
   }//GEN-LAST:event_textAreaKeyTyped

	// set second and third lines of output
	private void setLines2and3(KeyEvent evt)
	{
		line2 = String.format("This key is %san action key",
			(evt.isActionKey() ? "" : "not "));

		String temp = KeyEvent.getKeyModifiersText(evt.getModifiers());

		line3 = String.format("Modifier keys pressed: %s",
			(temp.equals("") ? "none" : temp)); // output modifiers

		textArea.setText(String.format("%s\n%s\n%s\n",
			line1, line2, line3)); // output three lines of text
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[])
	{
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try
		{
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
			{
				if ("Nimbus".equals(info.getName()))
				{
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		}
		catch (ClassNotFoundException ex)
		{
			java.util.logging.Logger.getLogger(KeyDemoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		catch (InstantiationException ex)
		{
			java.util.logging.Logger.getLogger(KeyDemoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		catch (IllegalAccessException ex)
		{
			java.util.logging.Logger.getLogger(KeyDemoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		catch (javax.swing.UnsupportedLookAndFeelException ex)
		{
			java.util.logging.Logger.getLogger(KeyDemoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable()
		{
			public void run()
			{
				new KeyDemoFrame().setVisible(true);
			}
		});
	}

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JTextArea textArea;
   // End of variables declaration//GEN-END:variables
}
